language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-ws-started *
  - mkdir -p deploy
  - mv springboot-ws-started.zip deploy/springboot-ws-started.zip

deploy:
  -provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
  secret_access_key: $ACCESS_SECRET_KEY # Travis repo settings 에 설정된 값
  bucket: sixstar6-aws-build # s3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: private # zip 파일 접근을 private 으로
  local_dir: deploy # before_deploy 에서 생성한 디렉토리
  wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - sixstar6@naver.com